travis:
  secure:
    BINSTAR_TOKEN: hrTodNml3/yasxBYRzLc64sqYS5I+vNYZq4Oxy3RSMYjGfRA4BRoVrTK+IG68nvip1XcveU6zPLD1s2EIZm5MTBe0W1pzWBCx9Y//KOiX8ehOKG2rEwoOK+ILn0VzMzgAXAU4uvqPWckapSV9ssqXv9VWl9LZ6GCLbmfp6W+Vm9/swA26V1rptgETKRGRTp+HrK9aI/UFQDckF2lK4Ijn3ZYmrIgRU9FqTgNXLYY2gRuZRTp3tg32/0X6Phoihet01XcGHHWs2KspKaLZF1V5sD5nCkT+0vBy+YzCSaKKzgrewrvu/xXOwpKj5cvry6cbN3zyc/yyROEun5LYDERd1wwEZ2WtNB1cWZo8TocCf0Z6mJAdCOTL7CvgfcmiLH93Q40MWq6dQjccqwzNz467SiGIJZDV75QFGh2fy/d+P3OPpYFqa7fuVVuNM+Bnv9AorgqlDN8hAHbh8Yz+AnECH34D976UBZr0Fe2ZJVlI1QHXR7GenAKCGN2YfcUFt1d+Ll+VqJo8wq0+FfeWSFkXDXHb4v+Xum330j3h1yyh+PJPVTqIjKM/QsUlGYCvlTIWNfmjMHGmkbn389eNdV9w/nyaROxK+foYlHjS0Yd5WVTnFHnCr6OvvM5wFykXrtYZLySlHo7G9/4nWn0UPME39n3Po9SupXkbjfJ+5n0Tg8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
