travis:
  secure:
    BINSTAR_TOKEN: dli1QTOammQ5rFwKdMtkYntxGVaXWgqJMulVEZHlX4uLBPIZ71H9HWvW7H7n8NW5ZZHq20ffKD/taYxe+OP/avGyXY/BiHxou95vahSapgPdGk7pZ4PeOM2kib6zT+vjTISL/S9Hpvq7yqPc/8YLRCVhiM1JaC0bjcw5x4aKmSUI01zj1EM2W89DpV8ORj3/Nzj0I3WWbcN3/ULkhVwYgm+KY/thaP1IYb7i2Zx7zeLPbkn+SqhJCaMX8B3GmVhrOhO8JF3gcHEPoZaOeEXGxVcWOvABeznGui1KBiM7r+D32/7XurI1+/dUdzaTHEj28EYHAZjzxvkk6gGyDlxW9ls6JsYPtgRDtdjfO+hOeBpQ/LtdYFxbaeeo1Q8RfRAI48YsM40QrbQOqG/0LL/2vbMUDKWJlGawEvpkqA7RYzS8Kbgw0PZtavWLGUVzBVJDEz3JI3bhW+yqsZrbj2wAVtBFCUkhvbuQ2/y95zaZ64+VDVP0vnRBL9PDaUan6QimwL2ajSV0cI5NkbSiu+ZPxTVPAUXm3Dze2uw0YdNBWvBjmYJlIndQyFJQ4CkRI15Ip/MBstWWsbQ0bSp0SGUrcQWd7X+dYXelnYs8L/aWFOdtQCAODD4BQwOiFawfefCNH1T9RJ5QJtc+NdV2Qj9AaqPjU3/KTuMAJm1tT0+uzDM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
