travis:
  secure:
    BINSTAR_TOKEN: Xp9kX7fvvJ9C7k5k1ZmyHkayCXa6czYqvYjtL/PJgFs+bc3GdoFtVtft9Oy6CMA60ubCcG9we6E6a92OhcWvhez17Y1C3kLrclFx0cwBNGkku1kXUq1cvEPwQU0QPbCIigwmYftX0e0ZTFfw3E7qeyNKmRfZyUvpyfNluWpwa+FvefdKBPgJQSVG5u8VDFTopdoVeGT+GFjH2788RZf5Ltkuvy6mrv+vRySJuAtZg/0Od/wDCakXLgZMLsFh5ER7/BJpkhYs7wj0a/cIKlWTyrO6ZDsE1b0iBOPQsAM5U6NznY7WQjTUJfS3bmWEDSyrKyT6Zu9glJdfhTGDivuotMZLiViqS+Kxij9eGu3Dzs5uyayDnPizUmCvYh/GAHE71UAXmOmnd5IVR3cqS4LNA9ptDrkxZI//o8qZiyaDUlUpnB9apmMiyvznnbEvgulhBjvgXllgveHt+4LpmQv/MAT4TTlMJa9SKd7UVrSEtCeB9L+LkMgM+fYuscUtOsvwgl+dEk7YEq6FrUA2r+zBaoqc/WmjsCfCZDGp9Om8Mc3H2WgapzD7a2Zp/29DhQsYa5QGYmdaPTlkHgDbbwBBqVnb79HvzC4txonW/DuaXS3yyzUv7+9JI6GDsLX9cLVZ0TDigIjIXKYuRTl0M1m4/GHgU3dKz/CiJEpCchD78pQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
